routes/web.php
<?php

use App\Http\Controllers\Cart\AddCartItemController;
use App\Http\Controllers\Cart\CartDetailController;
use App\Http\Controllers\Cart\CheckoutController;
use App\Http\Controllers\Cart\RemoveCartItemController;
use App\Http\Controllers\Cart\RemoveCouponController;
use App\Http\Controllers\Cart\UseCouponController;
use App\Http\Controllers\Orders\OrderDetailController;
use App\Http\Controllers\Orders\OrderIndexController;
use App\Http\Controllers\Orders\OrderPdfController;
use App\Http\Controllers\Orders\OrderPdfPreviewController;
use App\Http\Controllers\Payment\FailController;
use App\Http\Controllers\Payment\PayController;
use App\Http\Controllers\Products\ProductIndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ProductIndexController::class);

Route::prefix('cart')->group(function () {
    Route::get('/', CartDetailController::class);
    Route::get('/add/{product}', AddCartItemController::class);
    Route::get('/remove/{cartItem}', RemoveCartItemController::class);

    Route::post('/checkout', CheckoutController::class);

    Route::post('/coupon/use', UseCouponController::class);
    Route::get('/coupon/remove', RemoveCouponController::class);
});

Route::prefix('orders')->group(function () {
    Route::get('/', OrderIndexController::class);
    Route::get('/{order}', OrderDetailController::class);
    Route::get('/{order}/pdf', OrderPdfController::class);
    Route::get('/{order}/pdf/preview', OrderPdfPreviewController::class);
});

Route::prefix('payments')->group(function () {
    Route::get('/pay/{payment}', PayController::class);
    Route::get('/fail/{payment}', FailController::class);
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

app/Http/Controllers/Orders/OrderDetailController.php
<?php

namespace App\Http\Controllers\Orders;

use App\Domain\Order\Projections\Order;

class OrderDetailController
{
    public function __invoke(Order $order)
    {
        return view('orders.detail', [
            'order' => $order,
        ]);
    }
}

app/Http/Controllers/Orders/OrderIndexController.php
<?php

namespace App\Http\Controllers\Orders;

use App\Domain\Customer\Customer;
use App\Domain\Order\Projections\Order;

class OrderIndexController
{
    public function __invoke(Customer $customer)
    {
        $orders = Order::whereCustomer($customer)->orderByDesc('created_at')->paginate();

        return view('orders.index', [
            'customer' => $customer,
            'orders' => $orders,
        ]);
    }
}

app/Http/Controllers/Orders/OrderPdfController.php
<?php

namespace App\Http\Controllers\Orders;

use App\Domain\Order\Projections\Order;

class OrderPdfController
{
    public function __invoke(Order $order)
    {
        if ($order->invoice_path) {
            return response()->file($order->invoice_path);
        }

        return view('orders.invoice_pending', [
            'order' => $order,
        ]);
    }
}

app/Http/Controllers/Orders/OrderPdfPreviewController.php
<?php

namespace App\Http\Controllers\Orders;

use App\Domain\Order\Projections\Order;

class OrderPdfPreviewController
{
    public function __invoke(Order $order)
    {
        return view('orders.invoice', [
            'order' => $order,
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    public ?string $title = null;

    public function __construct(?string $title = null)
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/PdfLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class PdfLayout extends Component
{

    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.pdf');
    }
}

resources/views/orders/detail.blade.php
@php
    /** @var \App\Domain\Order\Projections\Order $order */
@endphp

<x-app-layout :title="'Order ' . $order->order_number">
    <x-slot name="breadcrumb">
        <div class="mb-12 font-display text-4xl flex items-center space-x-4">
            <a class="underline hover:text-red-500" href="{{ action(\App\Http\Controllers\Orders\OrderIndexController::class) }}">My Orders</a> 
            <span class="text-gray-500 text-base">></span>
            <span>{{ $order->order_number }}</span>
        </div>
    </x-slot>

    <div class="grid grid-cols-2 gap-12 items-start">
        <section class="grid grid-cols-1 gap-4">
            @foreach($order->lines as $line)
                <x-product :title="$line->description" :amount="$line->amount" :price="format_money($line->total_item_price_including_vat)"/>
            @endforeach
        </section>

        <section>
            <div class="grid grid-cols-[1fr,auto]">
                <x-price-line label="Status">
                    <div class="{{ $order->state->color() }}">{{ $order->state->label() }}</div>
                </x-price-line>
                <x-price-line label="Total Item Price">
                    {{ format_money($order->total_item_price_including_vat) }}
                </x-price-line>
                @if($order->hasShippingCost())
                    <x-price-line label="Shipping">
                        {{ format_money($order->shipping_costs_including_vat) }}
                    </x-price-line>
                @endif
                @if($order->hasCoupon())
                    <x-price-line label="Shipping">
                        <x-slot name="label">
                            Coupon <code class="bg-gray-100 p-1 rounded">{{ $order->coupon_code }}</code>
                        </x-slot>

                        -{{ format_money($order->coupon_reduction) }}
                    </x-price-line>
                @endif
                <x-price-line label="Total Price" total>
                    {{ format_money($order->totalPrice()) }}
                </x-price-line>
            </div>

            <div class="mt-12 flex justify-end">
                @if($order->shouldBePaid())
                    <a class="underline hover:text-red-500 mr-4" href="{{ action(\App\Http\Controllers\Payment\FailController::class, [$order->payment]) }}">Cancel order</a>
                    <a href="{{ action(\App\Http\Controllers\Payment\PayController::class, [$order->payment]) }}">
                        <x-button type="button">Pay now</x-button>
                    </a>
                @endif

                @if($order->isPaid())
                    <a target="_blank" href="{{ action(\App\Http\Controllers\Orders\OrderPdfController::class, [$order]) }}">
                        <x-button type="button">PDF</x-button>
                    </a>
                @endif
            </div>
        </section>
    </div>
</x-app-layout>

resources/views/orders/index.blade.php
@php
    /** @var \Illuminate\Pagination\LengthAwarePaginator|\App\Domain\Order\Projections\Order[] $orders */
    /** @var \App\Domain\Order\Projections\Order $order */
@endphp

<x-app-layout title="My Orders">

    <table class="w-full">
        <thead>
            <tr class="bg-gray-50 border-b border-gray-200">
                <th class="text-left uppercase text-gray-600 text-xs px-4 py-2">
                    Order
                </th>
                <th class="text-left uppercase text-gray-600 text-xs px-4 py-2">
                    Status
                </th>
                <th class="text-left uppercase text-gray-600 text-xs px-4 py-2">
                    Created
                </th>
                <th class="text-left uppercase text-gray-600 text-xs px-4 py-2">
                    Total
                </th>
                <th class="text-left uppercase text-gray-600 text-xs px-4 py-2">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
                <tr class="border-b border-gray-200">
                    <td class="px-4 py-2">
                        <h2>
                            <a href="{{ action(\App\Http\Controllers\Orders\OrderDetailController::class, [$order]) }}" class="underline hover:text-red-500 font-bold">
                                {{ $order->order_number }}
                            </a>
                        </h2>
                    </td>
                    
                    <td class="px-4 py-2 {{ $order->state->color() }}">
                        {{ $order->state->label() }}
                    </td>
                    <td class="px-4 py-2">
                        {{ $order->created_at->format('Y-m-d H:i') }}
                    </td>
                    <td class="px-4 py-2 font-semibold">
                        {{ format_money($order->total_item_price_including_vat) }}
                    </td>

                    <td class="px-4 py-2 text-right whitespace-nowrap">
                        @if($order->shouldBePaid())
                            <a class="underline hover:text-red-500 mr-4" href="{{ action(\App\Http\Controllers\Payment\FailController::class, [$order->payment]) }}">Cancel order</a>
                            <a href="{{ action(\App\Http\Controllers\Payment\PayController::class, [$order->payment]) }}">
                                <x-button type="button">Pay Now</x-button>
                            </a>
                        @endif

                        @if($order->isPaid())
                            <a target="_blank" href="{{ action(\App\Http\Controllers\Orders\OrderPdfController::class, [$order]) }}">
                                <x-button type="button">PDF</x-button>
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="mx-auto mt-12">
        {{ $orders->links() }}
    </div>
</x-app-layout>

resources/views/orders/invoice.blade.php
@php
    /** @var \App\Domain\Order\Projections\Order $order */
@endphp

<x-pdf-layout>
    <div class="flex items-center">
        <x-logo class="w-8 h-8 mr-4"/>
        <span class="font-display font-black uppercase text-xl tracking-wider">Laravel Shop | Invoice</span>
    </div>
    <h2 class="my-12 font-display font-black text-4xl">
       {{ $order->order_number }}
    </h2>
    <div class="mt-12 grid grid-cols-2 gap-12 items-start">
        <section class="grid grid-cols-1 gap-4">
            @foreach($order->lines as $line)
                <x-product :title="$line->description" :amount="$line->amount" :price="format_money($line->total_item_price_including_vat)"/>
            @endforeach
        </section>

        <section>
            <div class="grid grid-cols-[1fr,auto]">
                <x-price-line label="Total Item Price">
                    {{ format_money($order->total_item_price_including_vat) }}
                </x-price-line>
                @if($order->hasShippingCost())
                    <x-price-line label="Shipping">
                        {{ format_money($order->shipping_costs_including_vat) }}
                    </x-price-line>
                @endif
                @if($order->hasCoupon())
                    <x-price-line label="Shipping">
                        <x-slot name="label">
                            Coupon <code class="bg-gray-100 p-1 rounded">{{ $order->coupon_code }}</code>
                        </x-slot>

                        -{{ format_money($order->coupon_reduction) }}
                    </x-price-line>
                @endif
                <x-price-line label="Total Price" total>
                    {{ format_money($order->totalPrice()) }}
                </x-price-line>
            </div>
        </section>
    </div>
</x-pdf-layout>

resources/views/orders/invoice_pending.blade.php
@php
    /** @var \App\Domain\Order\Projections\Order $order */
@endphp

<x-app-layout title="Invoice PDF">
    <x-note>
        Please hang on a few minutes, your invoice PDF is still being generated. You will also receive a mail with the invoice attached when it's done.
    </x-note>
</x-app-layout>